version: '3.1'

services:
  db:
    image: postgres
    restart: always
    environment:
<<<<<<< HEAD
      POSTGRES_USER: postgres
=======
      POSTGRES_USER: postegres
>>>>>>> heroku_prod
      POSTGRES_PASSWORD: root
    ports:
      - 5432:5432
  adminer:
    image: adminer
    restart: always
    ports:
      - 8085:8080
