spring:
  datasource:
    url: jdbc:mysql://localhost:3306/customer-api?useTimezone=true&serverTimezone=America/Sao_Paulo
    username: &dbUser root
    password: &dbPassword 123456
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update