spring:
  datasource:
    username: postgres
    password: 123
    url: jdbc:postgresql://localhost:5432/customer-api
  jpa:
    database: POSTGRESQL
    generate-ddl: true
    hibernate.ddl-auto: update
    show-sql: true