ALTER TABLE customers
    ADD COLUMN road VARCHAR(100) NOT NULL,
    ADD COLUMN number VARCHAR(5) NOT NULL,
    ADD COLUMN district VARCHAR(50) NOT NULL,
    ADD COLUMN city VARCHAR(50) NOT NULL,
    ADD COLUMN state VARCHAR(50) NOT NULL,
    ADD COLUMN complement VARCHAR(50)
