CREATE TABLE address (
    id VARCHAR(100) PRIMARY KEY,
    road VARCHAR(100) NOT NULL,
    district VARCHAR(100) NOT NULL,
    city VARCHAR(100) NOT NULL,
    state VARCHAR(50) NOT NULL,
    postalCode VARCHAR(8) NOT NULL UNIQUE
);
